# Generated by Django 2.0.6 on 2018-10-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_auto_20181010_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='image',
            field=models.FileField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.FileField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='path',
            field=models.FileField(default='', upload_to='files/audios/'),
        ),
    ]
